version: '2'

services:
  consul:
    image: consul:0.8.3
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - sky-net

  redis-server:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
    networks:
      - sky-net

  user-service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    image: user-service:1.0.0
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul
    networks:
      - sky-net

  file-upload-service:
    build:
      context: .
      dockerfile: file_upload_service/Dockerfile
    image: file-upload-service:1.0.0
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul
    networks:
      - sky-net

  filemetadata-service:
    build:
      context: .
      dockerfile: file_meta_data_service/Dockerfile
    image: filemetadata-service:1.0.0
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
    depends_on:
      - consul
      - redis-server
    networks:
      - sky-net

  api-gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    image: api-gateway:1.0.0
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "8080:8080"
    depends_on:
      - consul
      - user-service
      - filemetadata-service
      - file-upload-service
    networks:
      - sky-net
volumes:
  redis:
    driver: local
networks:
  sky-net:
    driver: bridge
